name: ci
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!master'
    paths-ignore:
      - 'README.md'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Installing dependancies
        run: yarn
      - name: Linting files
        run: yarn lint
      - name: Running tests
        run: yarn test:unit
      - name: Running security-audit
        run: yarn security-audit

